# Generated by Django 4.0.10 on 2024-03-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chiphi',
            fields=[
                ('id_chiphi', models.CharField(db_column='Id_ChiPhi', max_length=20, primary_key=True, serialize=False)),
                ('ten', models.CharField(blank=True, db_column='Ten', max_length=20, null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', max_length=100, null=True)),
                ('gia', models.FloatField(blank=True, db_column='Gia', null=True)),
            ],
            options={
                'db_table': 'ChiPhi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chitietdonhang',
            fields=[
                ('id_chitietdonhang', models.BigIntegerField(db_column='id_ChiTietDonHang', primary_key=True, serialize=False)),
                ('trongluongnet_kg_field', models.FloatField(blank=True, db_column='TrongLuongNet(KG)', null=True)),
                ('trongluonggross_kg_field', models.FloatField(blank=True, db_column='TrongLuongGross(KG)', null=True)),
                ('trongluongnet_chai_kg_field', models.FloatField(blank=True, db_column='TrongLuongNet/Chai(KG)', null=True)),
                ('soluongthung', models.FloatField(blank=True, db_column='SoLuongThung', null=True)),
                ('giasanpham_kg', models.FloatField(blank=True, db_column='GiaSanPham/KG', null=True)),
                ('soluongchai', models.BigIntegerField(blank=True, db_column='SoLuongChai', null=True)),
                ('trongluongnet_thung_kg_field', models.FloatField(blank=True, db_column='TrongLuongNet/Thung(KG)', null=True)),
                ('trongluonggross_thung_kg_field', models.FloatField(blank=True, db_column='TrongLuongGross/Thung(KG)', null=True)),
                ('tonggiasanpham', models.FloatField(blank=True, db_column='TongGiaSanPham', null=True)),
                ('soluongchai_thung', models.IntegerField(blank=True, db_column='SoLuongChai/Thung', null=True)),
            ],
            options={
                'db_table': 'ChiTietDonhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donhang',
            fields=[
                ('id_donhang', models.BigIntegerField(db_column='id_DonHang', primary_key=True, serialize=False)),
                ('ngay', models.DateTimeField(blank=True, db_column='Ngay', null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', max_length=100, null=True)),
                ('contractno', models.CharField(blank=True, db_column='ContractNo', max_length=100, null=True)),
                ('shippingline', models.CharField(blank=True, db_column='ShippingLine', max_length=100, null=True)),
                ('shippedper', models.CharField(blank=True, db_column='ShippedPer', max_length=100, null=True)),
                ('portofloading', models.CharField(blank=True, db_column='PortOfLoading', max_length=100, null=True)),
                ('placeofdelivery', models.CharField(blank=True, db_column='PlaceOfDelivery', max_length=100, null=True)),
                ('sailingon', models.CharField(blank=True, db_column='SailingOn', max_length=100, null=True)),
                ('billofladingno', models.CharField(blank=True, db_column='BillOfLadingNo', max_length=100, null=True)),
                ('container_sealno', models.CharField(blank=True, db_column='Container/SealNo', max_length=100, null=True)),
                ('tongsoluong', models.FloatField(blank=True, db_column='TongSoLuong', null=True)),
                ('tonggia', models.FloatField(blank=True, db_column='TongGia', null=True)),
                ('donvigiatien', models.CharField(blank=True, db_column='DonViGiaTien', max_length=100, null=True)),
                ('bookingno', models.CharField(blank=True, db_column='BookingNo', max_length=100, null=True)),
            ],
            options={
                'db_table': 'DonHang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('id_khachhang', models.CharField(db_column='id_KhachHang', max_length=100, primary_key=True, serialize=False)),
                ('ten', models.CharField(blank=True, db_column='Ten', max_length=100, null=True)),
                ('diachi', models.CharField(blank=True, db_column='DiaChi', max_length=100, null=True)),
                ('quocgia', models.CharField(blank=True, db_column='QuocGia', max_length=100, null=True)),
                ('hoatdong', models.BigIntegerField(blank=True, db_column='HoatDong', null=True)),
                ('sdt', models.TextField(blank=True, db_column='SDT', null=True)),
                ('fax', models.TextField(blank=True, db_column='FAX', null=True)),
                ('zipcode', models.TextField(blank=True, db_column='ZipCode', null=True)),
            ],
            options={
                'db_table': 'KhachHang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loaichiphi',
            fields=[
                ('id_loaichiphi', models.CharField(db_column='Id_LoaiChiPhi', max_length=100, primary_key=True, serialize=False)),
                ('ten', models.CharField(db_column='Ten', max_length=100)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', max_length=100, null=True)),
            ],
            options={
                'db_table': 'LoaiChiPhi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loainguyenlieu',
            fields=[
                ('id_loainguyenlieu', models.CharField(db_column='Id_LoaiNguyenLieu', max_length=100, primary_key=True, serialize=False)),
                ('ten', models.CharField(db_column='Ten', max_length=100)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', max_length=100, null=True)),
            ],
            options={
                'db_table': 'LoaiNguyenLieu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nguyenlieu',
            fields=[
                ('id_nguyenlieu', models.CharField(db_column='Id_NguyenLieu', max_length=100, primary_key=True, serialize=False)),
                ('ten', models.CharField(blank=True, db_column='Ten', max_length=100, null=True)),
                ('gia', models.FloatField(blank=True, db_column='Gia', null=True)),
                ('xuatxu', models.CharField(blank=True, db_column='XuatXu', max_length=100, null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', max_length=100, null=True)),
            ],
            options={
                'db_table': 'NguyenLieu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sanpham',
            fields=[
                ('id_sanpham', models.CharField(db_column='Id_SanPham', max_length=100, primary_key=True, serialize=False)),
                ('ten', models.CharField(db_column='Ten', max_length=100)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', max_length=100, null=True)),
            ],
            options={
                'db_table': 'SanPham',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SanphamNguyenlieu',
            fields=[
                ('id', models.BigIntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('trongluong', models.FloatField(blank=True, db_column='TrongLuong', null=True)),
            ],
            options={
                'db_table': 'SanPham_NguyenLieu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SanphamOld',
            fields=[
                ('id_sanpham_old', models.CharField(db_column='Id_SanPham_Old', max_length=100, primary_key=True, serialize=False)),
                ('ten', models.CharField(blank=True, db_column='Ten', max_length=100, null=True)),
                ('xuatxu', models.CharField(blank=True, db_column='XuatXu', max_length=100, null=True)),
            ],
            options={
                'db_table': 'SanPham_Old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TuybienChiphi',
            fields=[
                ('id_tuybien_chiphi', models.BigIntegerField(db_column='Id_Tuybien_Chiphi', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TuyBien_ChiPhi',
                'managed': False,
            },
        ),
    ]
