# Generated by Django 4.0.10 on 2024-03-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_sql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giasanpham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nguyenlieu', models.CharField(db_column='Id_NguyenLieu', max_length=100)),
                ('Ten', models.CharField(db_column='Ten', max_length=200)),
                ('Trongluong', models.FloatField(db_column='tl')),
                ('Gia', models.FloatField(db_column='gia')),
            ],
            options={
                'db_table': 'final_sp_gia',
                'managed': False,
            },
        ),
    ]
