# Generated by Django 4.0.10 on 2024-07-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_sql', '0002_giasanpham'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Giasanpham',
        ),
    ]
