# Generated by Django 5.0.3 on 2024-07-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_sql', '0003_delete_giasanpham'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chitietdonhang',
            table='ChiTietDonHang',
        ),
    ]
