# Generated by Django 5.0.3 on 2024-04-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chiphi',
            fields=[
                ('id_chiphi', models.CharField(db_column='Id_ChiPhi', primary_key=True, serialize=False)),
                ('ten', models.CharField(blank=True, db_column='Ten', null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
                ('gia', models.FloatField(blank=True, db_column='Gia', null=True)),
            ],
            options={
                'db_table': 'ChiPhi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chitietdonhang',
            fields=[
                ('id_chitietdonhang', models.BigIntegerField(db_column='id_ChiTietDonHang', primary_key=True, serialize=False)),
                ('trongluongnet_kg_field', models.FloatField(blank=True, db_column='TrongLuongNet(KG)', null=True)),
                ('trongluonggross_kg_field', models.FloatField(blank=True, db_column='TrongLuongGross(KG)', null=True)),
                ('trongluongnet_chai_kg_field', models.FloatField(blank=True, db_column='TrongLuongNet/Chai(KG)', null=True)),
                ('soluongthung', models.FloatField(blank=True, db_column='SoLuongThung', null=True)),
                ('giasanpham_kg', models.FloatField(blank=True, db_column='GiaSanPham/KG', null=True)),
                ('soluongchai', models.BigIntegerField(blank=True, db_column='SoLuongChai', null=True)),
                ('trongluongnet_thung_kg_field', models.FloatField(blank=True, db_column='TrongLuongNet/Thung(KG)', null=True)),
                ('trongluonggross_thung_kg_field', models.FloatField(blank=True, db_column='TrongLuongGross/Thung(KG)', null=True)),
                ('tonggiasanpham', models.FloatField(blank=True, db_column='TongGiaSanPham', null=True)),
                ('soluongchai_thung', models.IntegerField(blank=True, db_column='SoLuongChai/Thung', null=True)),
            ],
            options={
                'db_table': 'ChiTietDonHang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dichvu',
            fields=[
                ('id_dichvu', models.CharField(db_column='Id_DichVu', primary_key=True, serialize=False)),
                ('tendichvu', models.CharField(blank=True, db_column='TenDichVu', null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'db_table': 'DichVu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donhang',
            fields=[
                ('id_donhang', models.BigIntegerField(db_column='id_DonHang', primary_key=True, serialize=False)),
                ('ngay', models.DateTimeField(blank=True, db_column='Ngay', null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
                ('contractno', models.CharField(blank=True, db_column='ContractNo', null=True)),
                ('shippingline', models.CharField(blank=True, db_column='ShippingLine', null=True)),
                ('shippedper', models.CharField(blank=True, db_column='ShippedPer', null=True)),
                ('portofloading', models.CharField(blank=True, db_column='PortOfLoading', null=True)),
                ('placeofdelivery', models.CharField(blank=True, db_column='PlaceOfDelivery', null=True)),
                ('sailingon', models.CharField(blank=True, db_column='SailingOn', null=True)),
                ('billofladingno', models.CharField(blank=True, db_column='BillOfLadingNo', null=True)),
                ('container_sealno', models.CharField(blank=True, db_column='Container/SealNo', null=True)),
                ('tongsoluong', models.FloatField(blank=True, db_column='TongSoLuong', null=True)),
                ('tonggia', models.FloatField(blank=True, db_column='TongGia', null=True)),
                ('donvigiatien', models.CharField(blank=True, db_column='DonViGiaTien', null=True)),
                ('bookingno', models.CharField(blank=True, db_column='BookingNo', null=True)),
            ],
            options={
                'db_table': 'DonHang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hopdong',
            fields=[
                ('id_hopdong', models.CharField(db_column='Id_HopDong', primary_key=True, serialize=False)),
                ('ten', models.CharField(blank=True, db_column='Ten', null=True)),
                ('sohd', models.CharField(blank=True, db_column='SoHD', null=True)),
                ('thoigianthue', models.BigIntegerField(blank=True, db_column='ThoiGianThue', null=True)),
                ('kythanhtoan_thang_lan_field', models.BigIntegerField(blank=True, db_column='KyThanhToan(thang/lan)', null=True)),
                ('tongthu', models.FloatField(blank=True, db_column='TongThu', null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'db_table': 'HopDong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HopdongDichvu',
            fields=[
                ('id_hopdongdichvu', models.CharField(db_column='Id_HopDongDichVu', primary_key=True, serialize=False)),
                ('dientich_soluong', models.FloatField(blank=True, db_column='DienTich_SoLuong', null=True)),
                ('dongia', models.FloatField(blank=True, db_column='DonGia', null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'db_table': 'HopDong_DichVu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('id_khachhang', models.CharField(db_column='id_KhachHang', primary_key=True, serialize=False)),
                ('ten', models.CharField(blank=True, db_column='Ten', null=True)),
                ('diachi', models.CharField(blank=True, db_column='DiaChi', null=True)),
                ('quocgia', models.CharField(blank=True, db_column='QuocGia', null=True)),
                ('hoatdong', models.BigIntegerField(blank=True, db_column='HoatDong', null=True)),
                ('sdt', models.TextField(blank=True, db_column='SDT', null=True)),
                ('fax', models.TextField(blank=True, db_column='FAX', null=True)),
                ('zipcode', models.TextField(blank=True, db_column='ZipCode', null=True)),
            ],
            options={
                'db_table': 'KhachHang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kheuocvay',
            fields=[
                ('id_kheuoc', models.AutoField(db_column='Id_KheUoc', primary_key=True, serialize=False)),
                ('tenkheuoc', models.CharField(db_column='TenKheUoc')),
                ('sotienvay', models.FloatField(blank=True, db_column='SoTienVay', null=True)),
                ('laisuat_nam', models.FloatField(blank=True, db_column='LaiSuat/Nam', null=True)),
                ('ngayvay', models.DateField(blank=True, db_column='NgayVay', null=True)),
                ('thoigianvay', models.CharField(blank=True, db_column='ThoiGianVay', null=True)),
                ('hinhthuctravay', models.CharField(blank=True, db_column='HinhThucTraVay', null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'db_table': 'KheUocVay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loaichiphi',
            fields=[
                ('id_loaichiphi', models.CharField(db_column='Id_LoaiChiPhi', primary_key=True, serialize=False)),
                ('ten', models.CharField(db_column='Ten')),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'db_table': 'LoaiChiPhi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loaidichvu',
            fields=[
                ('id_loaidichvu', models.CharField(db_column='Id_LoaiDichVu', primary_key=True, serialize=False)),
                ('tenloaidichvu', models.CharField(db_column='TenLoaiDichVu')),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'db_table': 'LoaiDichVu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loainguyenlieu',
            fields=[
                ('id_loainguyenlieu', models.CharField(db_column='Id_LoaiNguyenLieu', primary_key=True, serialize=False)),
                ('ten', models.CharField(db_column='Ten')),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'db_table': 'LoaiNguyenLieu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loaitaisan',
            fields=[
                ('id_loaitaisan', models.CharField(db_column='Id_LoaiTaiSan', primary_key=True, serialize=False)),
                ('tenloaitaisan', models.CharField(db_column='TenLoaiTaiSan')),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'db_table': 'LoaiTaiSan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nguyenlieu',
            fields=[
                ('id_nguyenlieu', models.CharField(db_column='Id_NguyenLieu', primary_key=True, serialize=False)),
                ('ten', models.CharField(blank=True, db_column='Ten', null=True)),
                ('gia', models.FloatField(blank=True, db_column='Gia', null=True)),
                ('xuatxu', models.CharField(blank=True, db_column='XuatXu', null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'db_table': 'NguyenLieu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sanpham',
            fields=[
                ('id_sanpham', models.CharField(db_column='Id_SanPham', primary_key=True, serialize=False)),
                ('ten', models.CharField(db_column='Ten')),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'db_table': 'SanPham',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SanphamNguyenlieu',
            fields=[
                ('id', models.BigIntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('trongluong', models.FloatField(blank=True, db_column='TrongLuong', null=True)),
            ],
            options={
                'db_table': 'SanPham_NguyenLieu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SanphamOld',
            fields=[
                ('id_sanpham_old', models.CharField(db_column='Id_SanPham_Old', primary_key=True, serialize=False)),
                ('ten', models.CharField(blank=True, db_column='Ten', null=True)),
                ('xuatxu', models.CharField(blank=True, db_column='XuatXu', null=True)),
            ],
            options={
                'db_table': 'SanPham_Old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taisan',
            fields=[
                ('id_taisan', models.BigAutoField(db_column='Id_TaiSan', primary_key=True, serialize=False)),
                ('tenloaitaisan', models.CharField(blank=True, db_column='TenLoaiTaiSan', null=True)),
                ('ngayghitang', models.DateField(blank=True, db_column='NgayGhiTang', null=True)),
                ('thoigiansudung', models.CharField(blank=True, db_column='ThoiGianSuDung', null=True)),
                ('nguyengia', models.FloatField(blank=True, db_column='NguyenGia', null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'db_table': 'TaiSan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TuybienChiphi',
            fields=[
                ('id_tuybien_chiphi', models.BigIntegerField(db_column='Id_Tuybien_Chiphi', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TuyBien_ChiPhi',
                'managed': False,
            },
        ),
    ]
